### PR TITLE
Fix failed Quality assurance step

### PR DESCRIPTION
**Pull request by peter279k**
# Changed log

- Using the `"wyrihaximus/html-compress": "^2.0 || ^4.0"` semver to be compatible with `php-8.0` version. And resolving following errors:

```
ou are using the deprecated option "--no-suggest". It has no effect and will break in Composer 3.
No lock file found. Updating dependencies instead of installing from lock file. Use composer update over composer install if you do not have a lock file.
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.
Error: Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - wyrihaximus/html-compress[2.0.0, ..., 2.0.1] require php ^7.2 -> your php version (8.0.0) does not satisfy that requirement.
    - Root composer.json requires wyrihaximus/html-compress ^2.0 -> satisfiable by wyrihaximus/html-compress[2.0.0, 2.0.1].


  Problem 1
    - wyrihaximus/html-compress[2.0.0, ..., 2.0.1] require php ^7.2 -> your php version (8.0.0) does not satisfy that requirement.
    - Root composer.json requires wyrihaximus/html-compress ^2.0 -> satisfiable by wyrihaximus/html-compress[2.0.0, 2.0.1].
```

- Fixing the failed Quality assurance step during GitHub Action building.

### CODE REVIEW

**Comment by peter279k** [comment]
It seems that the tests has been failed because the `wyrihaximus/html-compress` has the different behaviors on `^2.0` and `^4.0` versions.

It's the breaking changes. And I also recommend using the `wyrihaximus/html-compress:^3.0 || ^4.0` and fix failed assertions.

**Comment by oscarotero** [comment]
Yes, agree.
Could you update the requirements to `wyrihaximus/html-compress:^3.0 || ^4.0`?

**Comment by peter279k** [comment]
When using the `wyrihaximus/html-compress:^3.0 || ^4.0`, it should change the assertion on `testMinifier` method. And fix following error message:

```
PHPUnit 9.5.0 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.0.0
Configuration: /data/minifier/phpunit.xml.dist
Warning:       Your XML configuration validates against a deprecated schema.
Suggestion:    Migrate your XML configuration using "--migrate-configuration"!

F..                                                                 3 / 3 (100%)

Time: 00:00.058, Memory: 10.00 MB

There was 1 failure:

1) Middlewares\Tests\MinifierTest::testMinifier with data set #0 ('text/html', '<!DOCTYPE html>\n<html>\n    ...tml>\n', '<!DOCTYPE html><html><head><t...cript>')
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'<!DOCTYPE html><html><head><title>Title</title> <style type=text/css>body{background:blue;color:red}p+p{margin-top:10px}@media (min-width:300px){body{font-size:1.2em}}</style> <body><h1>Hello world!</h1> <script type=text/javascript>var colors={first:'blue',second:'red',third:'yellow',};var names=['foo','bar'];names.forEach(function(name){console.log(name);for(var i in colors){console.log(colors[i])}})</script>'
+'<!DOCTYPE html><html><head><title>Title</title><style>body{background:blue;color:red}p+p{margin-top:10px}@media (min-width:300px){body{font-size:1.2em}}</style> <body><h1>Hello world!</h1> <script>var colors={first:'blue',second:'red',third:'yellow',};var names=['foo','bar'];names.forEach(function(name){console.log(name);for(var i in colors){console.log(colors[i])}})</script>'

/data/minifier/tests/MinifyTest.php:53
```

**Comment by oscarotero** [comment]
Perfect. Thanks!

**Pull request merged**
